### ISSUE TITLE
Get HF Username in Session

### ISSUE THREAD

**Issue by XThomasBU** [DL4DS/dl4ds_tutor#11]
Need a way to get the Huggingface Username of the user in main.py, this could be a way to authenticate the user.

Gradio seems to support this (check: https://github.com/gradio-app/gradio/pull/4943, and https://huggingface.co/spaces/Wauplin/gradio-oauth-test). Need to extend this to Chainlit.

**Comment by trgardos** [comment]
Not relevant anymore since we're using Google OAuth
