### ISSUE TITLE
Improve Extraction of Content from Lecture Pdfs

### ISSUE THREAD

**Issue by XThomasBU** [DL4DS/dl4ds_tutor#13]
Get either a summary of the content in the lectures / a better way to extract structured text from the pdfs, to feed as context to RAG

**Comment by trgardos** [comment]
#22 is addressing this by improving content extraction.

Still open is to parse diagrams (generate text descriptions) and equations (into latex math notation).

**Comment by trgardos** [comment]
Closing with #22 addressing part of it.
