### ISSUE TITLE
SCRUM-77 Remove TinyLlama from repo and download and cache from code instead

### ISSUE THREAD

**Issue by trgardos** [DL4DS/dl4ds_tutor#38]
Right now the TinyLlama model is checked into the repo and tracked with LFS. Because of that we've hit our GitHub LFS bandwidth and storage limit. In general we shouldn't check in models into the repo. The only obvious solution is to change the code to download local models if not already cache, and cache the model in local storage to avoid downloading each time.  Ideally the model we download and cache is versioned, so we can optionally check for newer verisions of the model.

Tracked as JIRA story SCRUM-77.

**Comment by trgardos** [comment]
Once the change is made, I will scrub the git history of that model file.

**Comment by XThomasBU** [comment]
HF path to model: https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/tree/main
