### ISSUE TITLE
Error response with Llama model

### ISSUE THREAD

**Issue by trgardos** [DL4DS/dl4ds_tutor#8]
Get the following error when prompting Llama model.

```
1 validation error for LlamaCpp
root
Could not load Llama model from path: storage/models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf. Received error  (type=value_error)

'NoneType' object has no attribute 'acall'
```

**Comment by XThomasBU** [comment]
Need to work on fixing this, the lfs file pushed from git to HF is not pushing the whole file, and causes this error. Temporary fix: Upload the model directly on HF

**Comment by trgardos** [comment]
The ultimate fix is to not have the model checked in see: #38
